In [1]:
from asc_tree import asc_tree
import numpy as np
import matplotlib.pyplot as plt

simplicial_complex = asc_tree.ASC_Tree()
simplicial_complex.add_path(("Cow", "Rabbit"))
simplicial_complex.add_path(("Cow", "Horse"))
simplicial_complex.add_path(("Cow", "Dog"))
simplicial_complex.add_path(("Rabbit", "Horse"))
simplicial_complex.add_path(("Rabbit", "Dog"))
simplicial_complex.add_path(("Horse", "Dog"))
simplicial_complex.add_path(("Fish", "Dolphin"))
simplicial_complex.add_path(("Fish", "Oyster"))
simplicial_complex.add_path(("Dolphin", "Oyster"))
simplicial_complex.add_path(("Broccoli", "Fern"))
simplicial_complex.add_path(("Broccoli", "Onion"))
simplicial_complex.add_path(("Broccoli", "Apple"))
simplicial_complex.add_path(("Fern", "Onion"))
simplicial_complex.add_path(("Fern", "Apple"))
simplicial_complex.add_path(("Onion", "Apple"))
simplicial_complex.add_path(("Cow", "Rabbit", "Horse"))
simplicial_complex.add_path(("Cow", "Rabbit", "Dog"))
simplicial_complex.add_path(("Cow", "Horse", "Dog"))
simplicial_complex.add_path(("Rabbit", "Horse", "Dog"))
simplicial_complex.add_path(("Fish", "Dolphin", "Oyster"))
simplicial_complex.add_path(("Broccoli", "Fern", "Onion"))
simplicial_complex.add_path(("Broccoli", "Fern", "Apple"))
simplicial_complex.add_path(("Broccoli", "Onion", "Apple"))
simplicial_complex.add_path(("Fern", "Onion", "Apple"))

print(simplicial_complex.get_paths())


[['Cow', 'Rabbit', 'Horse'], ['Cow', 'Rabbit', 'Dog'], ['Cow', 'Rabbit'], ['Cow', 'Horse', 'Dog'], ['Cow', 'Horse'], ['Cow', 'Dog'], ['Cow'], ['Rabbit', 'Horse', 'Dog'], ['Rabbit', 'Horse'], ['Rabbit', 'Dog'], ['Rabbit'], ['Horse', 'Dog'], ['Horse'], ['Dog'], ['Fish', 'Dolphin', 'Oyster'], ['Fish', 'Dolphin'], ['Fish', 'Oyster'], ['Fish'], ['Dolphin', 'Oyster'], ['Dolphin'], ['Oyster'], ['Broccoli', 'Fern', 'Onion'], ['Broccoli', 'Fern', 'Apple'], ['Broccoli', 'Fern'], ['Broccoli', 'Onion', 'Apple'], ['Broccoli', 'Onion'], ['Broccoli', 'Apple'], ['Broccoli'], ['Fern', 'Onion', 'Apple'], ['Fern', 'Onion'], ['Fern', 'Apple'], ['Fern'], ['Onion', 'Apple'], ['Onion'], ['Apple']]


In [2]:
mat, rows, cols = simplicial_complex.get_boundary_matrix(3)

In [3]:
mat.shape, len(rows), len(cols)

((15, 9), 15, 9)

In [4]:
y_label_list

NameError: name 'y_label_list' is not defined

In [ ]:
fig,ax = plt.subplots(1,1, figsize=(10,10))
ax.imshow(mat, cmap='gray')
x_label_list = list(map(lambda x: ",".join(list(x)),cols))
y_label_list = list(map(lambda x: ",".join(list(x)),rows))

ax.set_yticks(range(0,len(y_label_list)))
ax.set_xticks(range(0,len(x_label_list)))

ax.set_xticklabels(x_label_list,rotation=90)
ax.set_yticklabels(y_label_list)

In [ ]:
simplicial_complex.get_boundary_matrix(2)[2]

In [5]:
# simplicial_complex.add_path(("Cow", "Rabbit"))  (Cow, Rabbit) 
# simplicial_complex.add_path(("Cow", "Horse")) (Cow, Horse)
# simplicial_complex.add_path(("Rabbit", "Horse")) (Horse, Rabbit)
# simplicial_complex.add_path(("Rabbit", "Dog"))  (Dog, Rabbit)
# simplicial_complex.add_path(("Horse", "Dog"))    (Dog, Horse) 
# simplicial_complex.add_path(("Fish", "Dolphin"))  (Dolphin, Fish) 
# simplicial_complex.add_path(("Fish", "Oyster"))   (Fish, Oyster) 
# simplicial_complex.add_path(("Dolphin", "Oyster")) (Dolphin, Oyster)
# simplicial_complex.add_path(("Broccoli", "Fern"))   (Broccoli, Fern)
# simplicial_complex.add_path(("Broccoli", "Onion"))  (Broccoli, Onion)
# simplicial_complex.add_path(("Broccoli", "Apple"))  (Apple, Broccoli)
# simplicial_complex.add_path(("Fern", "Onion")) (Fern, Onion)
# simplicial_complex.add_path(("Fern", "Apple")) (Apple, Fern)
# simplicial_complex.add_path(("Onion", "Apple")) (Apple, Onion)

# (Cow, Dog)

In [35]:
import numpy as np

class Z2array(np.ndarray):
    """ class overloading a numpy array for addition
    """
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return np.abs(np.round(obj) % 2)

    def __array_finalize__(self, obj):
        return None
    
    def __add__(self,x):
        return Z2array(np.array(self) + np.array(x)) %2
    
    def __radd__(self,x):
        return Z2array(np.array(self) + np.array(x)) %2
    
    def __iadd__(self,x):
        return Z2array(np.array(self) + np.array(x)) %2
    
    def __mul__(self,x):
        return Z2array(np.array(self) * np.array(x))  %2
    
    def __rmul__(self,x):
        return Z2array(np.array(self) * np.array(x)) %2
    
    def __imul__(self,x):
        return Z2array(np.array(self) * np.array(x)) %2
    
    def __sub__(self,x):
        return Z2array(np.array(self) - np.array(x)) %2
    
    def __rsub__(self,x):
        return Z2array(np.array(self) - np.array(x)) %2
    
    def __isub__(self,x):
        return Z2array(np.array(self) - np.array(x)) %2
    
    def __div__(self, scalar):
        return self
    
    def __rdiv__(self, scalar):
        return self
    
    def __idiv__(self, scalar):
        return self
    
    def __floordiv__(self, scalar):
        return self
    
    def __truediv__(self, scalar):
        return self

    def __array__(self):
        """ so that numpy's array() returns values
        """
        return self
    
#     def __array_wrap__(self, out_arr, context=None):
# #         print('In __array_wrap__:')
# #         print('   self is %s' % repr(self))
# #         print('   arr is %s' % repr(out_arr))
#         # then just call the parent
#         return super(Z2array, self).__array_wrap__(self, out_arr, context)

#     def __repr__(self):
#         return "Z2 array of shape %s: \n %s" % (str(self.shape), str(self)[:100])

In [36]:
F = Z2array(mat)

In [55]:
F = mat == 1

In [56]:
np.dot(F , F.T )

array([[ True,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False],
       [ True,  True,  True,  True, False,  True, False, False, False,
        False, False, False, False, False, False],
       [ True,  True,  True, False,  True,  True, False, False, False,
        False, False, False, False, False, False],
       [ True,  True, False,  True,  True,  True, False, False, False,
        False, False, False, False, False, False],
       [ True, False,  True,  True,  True,  True, False, False, False,
        False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True,
        False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True,
        False, False, False, False, False, False],
       [False, False, Fa

In [57]:
scipy.linalg.solve(F, np.eye(F.shape[0], F.shape[1]))

ValueError: Input a needs to be a square matrix.

In [58]:
F - 20 *F

array([[-19, -19,   0,   0,   0,   0,   0,   0,   0],
       [-19,   0, -19,   0,   0,   0,   0,   0,   0],
       [  0, -19, -19,   0,   0,   0,   0,   0,   0],
       [-19,   0,   0, -19,   0,   0,   0,   0,   0],
       [  0, -19,   0, -19,   0,   0,   0,   0,   0],
       [  0,   0, -19, -19,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, -19,   0,   0,   0,   0],
       [  0,   0,   0,   0, -19,   0,   0,   0,   0],
       [  0,   0,   0,   0, -19,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, -19, -19,   0,   0],
       [  0,   0,   0,   0,   0, -19,   0, -19,   0],
       [  0,   0,   0,   0,   0,   0, -19, -19,   0],
       [  0,   0,   0,   0,   0, -19,   0,   0, -19],
       [  0,   0,   0,   0,   0,   0, -19,   0, -19],
       [  0,   0,   0,   0,   0,   0,   0, -19, -19]])

In [59]:
np.linalg.matrix_rank(F)

9

In [42]:
import scipy
P , L , U  = scipy.linalg.lu(F)

In [43]:
P @ L @ U  == F

Z2array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True, 

In [47]:
L

array([[ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -1. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  1. , -0.5,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  0. ,  1. ,  1. ,  0. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  0. ,  0. , -1. ,  1. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  0. ,  1. ,  1. , -0.5,  1. ],
       [ 0. , -0. ,  0.5,  1. ,  0. ,  0. , -0. ,  0. ,  0. ],
       [ 0. , -1. ,  0.5,  1. ,  0. ,  0. , -0. ,  0. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  1. ,  0. , -0. ,  0. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  1. ,  0. , -0. ,  0. ,  0. ],
       [ 0. , -0. ,  0. ,  0. ,  0. ,  0. , -1. ,  0.5,  1. ],
       [ 0. , -0. ,  0. ,  0. ,  0. ,  0. , -0. ,  0.5,  1. ]])

In [60]:
Q, R = scipy.linalg.qr(F)

In [61]:
Q, R

(array([[-5.77350259e-01,  4.08248276e-01,  3.16227823e-01,
          2.58198857e-01,  0.00000000e+00,  0.00000000e+00,
          8.02570721e-09, -4.01285360e-09,  8.00036393e-09,
         -2.91006237e-01, -3.12401623e-01, -9.94765013e-02,
         -3.29467952e-01, -1.16542794e-01, -1.37938187e-01],
        [-5.77350259e-01, -2.04124182e-01, -4.74341661e-01,
          2.58198887e-01,  0.00000000e+00,  0.00000000e+00,
         -1.32916989e-09,  6.64584943e-10,  1.94250287e-08,
         -3.22856265e-03,  5.54572456e-02,  2.72855788e-01,
          1.02268755e-01,  3.19667310e-01,  3.78353059e-01],
        [-0.00000000e+00,  6.12372458e-01, -4.74341661e-01,
          2.58198887e-01,  0.00000000e+00,  0.00000000e+00,
         -6.69653710e-09,  3.34826855e-09, -2.74253935e-08,
          2.94234812e-01,  2.56944418e-01, -1.73379317e-01,
          2.27199227e-01, -2.03124508e-01, -2.40414873e-01],
        [-5.77350259e-01, -2.04124182e-01,  1.58113867e-01,
         -5.16397774e-01,  0.00000000

In [34]:
Q 

array([[-5.77350269e-01,  4.08248290e-01,  3.16227766e-01,
         2.58198890e-01,  0.00000000e+00,  0.00000000e+00,
        -4.48471386e-17, -3.40401152e-17, -2.65655920e-17,
        -2.91006265e-01, -3.12401660e-01, -9.94764888e-02,
        -3.29467975e-01, -1.16542804e-01, -1.37938199e-01],
       [-5.77350269e-01, -2.04124145e-01, -4.74341649e-01,
         2.58198890e-01,  0.00000000e+00,  0.00000000e+00,
         7.42731758e-18, -2.95134198e-18, -4.18922825e-18,
        -3.22857039e-03,  5.54572308e-02,  2.72855792e-01,
         1.02268723e-01,  3.19667284e-01,  3.78353086e-01],
       [-0.00000000e+00,  6.12372436e-01, -4.74341649e-01,
         2.58198890e-01,  0.00000000e+00,  0.00000000e+00,
         3.74198211e-17,  3.69914571e-17,  3.07548203e-17,
         2.94234835e-01,  2.56944429e-01, -1.73379303e-01,
         2.27199252e-01, -2.03124481e-01, -2.40414887e-01],
       [-5.77350269e-01, -2.04124145e-01,  1.58113883e-01,
        -5.16397779e-01,  0.00000000e+00,  0.00000000

In [ ]:
R

In [62]:
scipy.linalg.svd(F)

(array([[-4.98861885e-09, -4.08248216e-01,  0.00000000e+00,
         -9.74504317e-08,  3.01660696e-09,  4.98861930e-09,
         -5.77350259e-01,  4.08248335e-01,  9.25463350e-09,
         -2.91006237e-01, -3.12401623e-01, -9.94765013e-02,
         -3.29467952e-01, -1.16542794e-01, -1.37938187e-01],
        [-5.73554182e-09, -4.08248305e-01,  0.00000000e+00,
          5.00000060e-01, -1.19590586e-08,  5.73554271e-09,
          2.88675129e-01,  4.08248246e-01,  1.30662974e-08,
         -3.22856265e-03,  5.54572456e-02,  2.72855788e-01,
          1.02268755e-01,  3.19667310e-01,  3.78353059e-01],
        [ 1.07241602e-08, -4.08248246e-01,  0.00000000e+00,
          5.00000000e-01,  8.94245211e-09, -1.07241629e-08,
         -2.88675219e-01, -4.08248305e-01, -2.23209309e-08,
          2.94234812e-01,  2.56944418e-01, -1.73379317e-01,
          2.27199227e-01, -2.03124508e-01, -2.40414873e-01],
        [ 1.07241611e-08, -4.08248305e-01,  0.00000000e+00,
         -4.99999970e-01,  8.94244945